WizardActivity: Fix build
/home/runner/work/App/App/app/src/main/java/org/andbootmgr/app/WizardActivity.kt:145: Error: Overriding method should call super.onBackPressed [MissingSuperCall]
 override fun onBackPressed() {
              ~~~~~~~~~~~~~

   Explanation for issues of type "MissingSuperCall":
   Some methods, such as View#onDetachedFromWindow, require that you also call
   the super implementation as part of your method.